[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
nom.workspace = true
pathfinding.workspace = true
simplex = "1"

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "benchmark"
harness = false
